### ISSUE TITLE
Add Region error !

### ISSUE THREAD

**Issue by bobys16** [ItzLevvie/Cigar#14]
i try to add 2 new Region the server is running fine .
but i try to add new one / third region console is showing error .

this

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at GameServer.startStatsServer (/root/Cigar-oga/server/GameServer.js:1120:21)
    at GameServer.start (/root/Cigar-oga/server/GameServer.js:292:10)
    at MasterServer.createServer (/root/Cigar-oga/server/MasterServer.js:219:8)
    at MasterServer.loadConfig (/root/Cigar-oga/server/MasterServer.js:141:22)
    at MasterServer.start (/root/Cigar-oga/server/MasterServer.js:75:10)
    at Object.<anonymous> (/root/Cigar-oga/server/index.js:55:18)

and this is my masterserver ini file 
serverIP = 51.254.157.61
serverPort = 80
gameserverPort = 1500
updateTime = 60
regions = {"A": 1, "FFA 1 - [Online]": 1, "FFA 2 - [Online]": 1}

Any helped will be appreciated :+1:

**Comment by MastaCoder** [comment]
Check gameserver2.ini and update the status port.

**Comment by bobys16** [comment]
serverStatsPort << This? .
that is port already taken by older / previous gameserver .ini ?

**Comment by bobys16** [comment]
Its Worked THANKSS :dancer:

**Comment by bobys16** [comment]
But how to add Region with Different Ip address??
Thanks

**Comment by MastaCoder** [comment]
Can't do that yet from what I know.

**Comment by bobys16** [comment]
Solved ... Already Create my own js to do that with the client script :dancer:  thanks
